### ISSUE TITLE
[FEATURE] Ability to Suppress Headers & Footers on Selected Pages (e.g., pages printed with front and back matter)

### ISSUE THREAD

**Issue by davidleejy** [Pablo-Gonzalez-Calderon/chic-header-package#6] opened 2023-10-02 07:19 UTC
Hi, I apologize for writing in with two issues at one go, and I hope this is not too overwhelming for you.

I'd like to propose considering an option for users to suppress the rendering of headers and footers on some pages as I've observed that it is customary to leave out headers and footers on some pages especially those containing front and back matter ([1] provides a nice reference on front and back matter). Pages that typically comprise the front matter are the title page, copyright page, dedication page, table of contents page, while pages that typically comprise the back matter are the bibliography, author's biography, and indexes.

I'm not sure what's the best way to go about implementing this feature but off the top of my head, I can think of _two_ ways:

**Option 1**. More of a _quick-fix_. Provide a parameter under `chic.with()` that lets users suppress headers and footer rendering for certain pages like:
```typst
#show: chic.with(
  // ...
  chic-suppress((1, 2, 3, -1)) // argument is an array indicated intention to suppress the rendition of headers and footers on pages 1, 2, 3, and the last page (denoted with -1).
)
```
This idea stems from the observation that pages without headers and footers typically make up the small handful of pages in the front and back of a document.

**Option 2**. Let users control when chic-hdr's engine is enabled and disabled:

```Typst

#import "@preview/chic-hdr:0.3.0": *

#show: chic.with(
  // ... user's settings ...
)

chic-off() // Disable chic-hdr's rendering of headers and footers in the front matter pages.

// Front Matter
= Title
#lorem(10)
#pagebreak()
= Copyright
#lorem(10)
#pagebreak()
= Dedication
#lorem(10)
#pagebreak()
// End Front Matter

chic-on() // Enable chic-hdr

= Introduction
#lorem(200)

= Motivation
#lorem(200)

// ... more content ...

chic-off() // Disable chic-hdr to suppress headers and footers in back matter pages.

// Back Matter
= Bibliography
#lorem(10)
#pagebreak()
= Author's Biography
#lorem(10)
#pagebreak()
= Index
#lorem(10)
#pagebreak()
// End Back Matter

``` 

Thank you for reading and considering this feature request. Hoping that this makes sense.

**References**

[1] Examples of Pages in the Front and Back Matter https://kdp.amazon.com/en_US/help/topic/GDDYZG2C7RVF5N9J

**Comment by Pablo-Gonzalez-Calderon** [comment] 2023-10-02 19:02
Hi again! 😁

Yeah, I thought that while creating the package, and it actually exist an option for doing it! The ``skip`` parameters allows you to give an array of integers indicating what pages mustn't have header and footer. Here's a screenshot of the [manual](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/blob/85a1e1bc9f536ec8605ea39f7a8de43aea0e76ed/Chic-header's%20Manual.pdf) describing the property:

![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/30756770/b764369d-9c52-41c6-8953-ba4e735437a4)
 
Tell me if this solves the Issue, or if the feature you wanted was something different 😉

**Comment by davidleejy** [comment] 2023-10-03 06:06
Hi Pablo, yeah, the `skip` argument would work. However, is there a possibility that it isn't implemented in v0.3.0? Using `skip` in this version causes Typst to raise an unexpected argument error 😞

**Comment by Pablo-Gonzalez-Calderon** [comment] 2023-10-03 15:45
Hi again! 😁

Hmmm. I think it could be because you put something like ``(1)`` instead ``(1,)``. Without the comma, Typst not recognizes that as an array type. I've put an *observation* to that in some parts of the manual, but it seems I've forgot to put one in the ``skip`` section. Here's a screenshot of it, if it helps to clarify the difference:

![image](https://github.com/Pablo-Gonzalez-Calderon/chic-header-package/assets/30756770/f852597f-5b1b-42c2-b20f-193e522b7501)

Tell me if this solves the error 😁 If not, I would appreciate if you can write the code you used to replicate the problem and try to fix it.

**Comment by davidleejy** [comment] 2023-10-04 15:24
Hi Pablo, glad to report that it works nicely now 🙂. Do you happen to have any good ideas on how to skip pages right at the back? Personally, this isn't an urgent request, but I just thought since this thread has opened the issue of skipping pages, thinking about skipping the pages right at the back might be timely.🤔

**Comment by Pablo-Gonzalez-Calderon** [comment] 2023-10-05 15:25
Hi David!

> Hi Pablo, glad to report that it works nicely now 🙂

I'm happy to hear that! 😁

> Do you happen to have any good ideas on how to skip pages right at the back?

Hmmm. Currently the only way to do it is changing the values in ``skip`` as the amount of pages increment. For example, if you want to skip last page --for instance, 5--, then you must set ``skip: (5,)``. And, if you write more pages before page 5, you must change the skipped page to the new last one --for instance, ``skip: (7,)``.

Thinking a while on this issue, maybe a good option would be to allow negative indexes. So, if the user put ``skip: (-1,)``, the last page is skipped.  This could be more direct than creating a, for example, ``chic-last-pages-index(amount: 3)`` function, which would be clumsier.

What do you think? 🤔Those are the ideas I can think by the moment.

**Comment by davidleejy** [comment] 2023-10-06 07:44
Hi Pablo!

Yeah, I am supportive of the negative indexes idea. Python, a popular programming language, has allowed negative indexes when indexing arrays for a long time (many many years) -- so it would appear that negative indexing is an idea that has been tried, tested and appears to be sensible.

**Comment by Pablo-Gonzalez-Calderon** [comment] 2023-10-09 04:23
Hi! 😁

It's been a couple of days, and I finally implemented the negative indexes. Now you can skip the setting of the header and the footer in the final pages by using negative indexes!

Also, I thought that probably the error that happened to you while using ``skip`` would be more common than I initially thought, so I decided to handle those cases, and now, if you write ``skip: (2)`` it will be the same as ``skip: (2,)``, in order to decrement the number of errors caused by the type mismatch 😉

I hope these changes work well for you. I'm going to close this Issue as it seems solved. Anyways, if you find something wrong with the code or behaviour of the new features, just re-open it and tell me what happened 😉

Thank you so much for the feedback given for this and Issue 5 features. Definitely this improved the package nicely. 😁

**Closed by Pablo-Gonzalez-Calderon** 2023-10-09 04:23 UTC
Labels: enhancement
